title: "The Quiet Before the Storm: NYC's Pandemic Noise Story"
description: "Exploring how COVID-19 transformed New York City's soundscape through noise complaint data"
baseurl: "/nycity-noise-story"
url: "https://LeoItaly.github.io"

# Author information
author:
  name: LeoItaly
  email: example@example.com
  github: LeoItaly
  twitter:
  linkedin:

# Build settings
markdown: kramdown
# Commenting out theme to use custom Sass files
# theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Sass processing
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules
  sourcemap: never

# Theme customization - using blues, oranges, and greens as mentioned
accent_color: "#3182bd" # Blue from visualizations
theme_color: "#333333"
theme_font: "Nunito Sans"

# SEO settings
twitter:
  username:
  card: summary_large_image
logo: /assets/images/site-icon.png
social:
  name: "The Quiet Before the Storm: NYC's Pandemic Noise Story"
  links:
    - https://github.com/LeoItaly/nycity-noise-story

# Collections
collections:
  data:
    output: true
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  publications:
    output: true
    permalink: /publications/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: /assets/images/default-banner.jpg
  - scope:
      path: "_posts"
    values:
      layout: "post"
      author: "LeoItaly"
  - scope:
      path: "_publications"
    values:
      layout: "publication"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
